version: 0.2

env:
  variables:
    ACCOUNT_ID: 084828586975
    REGION: us-east-1
    FRONTEND_REPO: three-tier-frontend
    BACKEND_REPO: three-tier-backend
    FRONTEND_DIR: Application-Code/frontend
    BACKEND_DIR: Application-Code/backend
    K8S_MANIFEST_DIR: Kubernetes-Manifests-file

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing utilities...
      - yum install -y jq

  pre_build:
    commands:
      - echo Setting dynamic image tag...
      - export IMAGE_TAG=v1.${CODEBUILD_BUILD_NUMBER}
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com
      - echo Installing frontend and backend dependencies...
      - cd $FRONTEND_DIR && npm install && cd -
      - cd $BACKEND_DIR && npm install && cd -

  build:
    commands:
      - echo Building Docker images...
      - docker build -t $FRONTEND_REPO:$IMAGE_TAG $FRONTEND_DIR
      - docker tag $FRONTEND_REPO:$IMAGE_TAG ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/$FRONTEND_REPO:$IMAGE_TAG
      - docker build -t $BACKEND_REPO:$IMAGE_TAG $BACKEND_DIR
      - docker tag $BACKEND_REPO:$IMAGE_TAG ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/$BACKEND_REPO:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing Docker images to ECR...
      - docker push ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/$FRONTEND_REPO:$IMAGE_TAG
      - docker push ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/$BACKEND_REPO:$IMAGE_TAG

      - echo Replacing image placeholders in Kubernetes manifests...
      - mkdir -p k8s-out/Frontend k8s-out/Backend k8s-out/Database

      # Replace frontend image
      - sed "s|IMAGE_PLACEHOLDER|${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/$FRONTEND_REPO:$IMAGE_TAG|g" $K8S_MANIFEST_DIR/Frontend/deployment.yaml > k8s-out/Frontend/deployment.yaml
      - cp $K8S_MANIFEST_DIR/Frontend/service.yaml k8s-out/Frontend/service.yaml

      # Replace backend image
      - sed "s|IMAGE_PLACEHOLDER|${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/$BACKEND_REPO:$IMAGE_TAG|g" $K8S_MANIFEST_DIR/Backend/deployment.yaml > k8s-out/Backend/deployment.yaml
      - cp $K8S_MANIFEST_DIR/Backend/service.yaml k8s-out/Backend/service.yaml

      # Copy DB manifests
      - cp $K8S_MANIFEST_DIR/Database/*.yaml k8s-out/Database/

      # Copy ingress
      - cp $K8S_MANIFEST_DIR/ingress.yaml k8s-out/ingress.yaml

      # Flatten for CodePipeline deploy stage
      - cp k8s-out/Frontend/deployment.yaml k8s-out/deployment-frontend.yaml
      - cp k8s-out/Frontend/service.yaml k8s-out/service-frontend.yaml
      - cp k8s-out/Backend/deployment.yaml k8s-out/deployment-backend.yaml
      - cp k8s-out/Backend/service.yaml k8s-out/service-backend.yaml
      - cp k8s-out/Database/*.yaml k8s-out/
      - cp k8s-out/ingress.yaml k8s-out/


      # - echo Replacing image placeholders in Kubernetes manifests...
      # - mkdir -p k8s-out/Frontend k8s-out/Backend

      # - mkdir -p k8s-out/Frontend k8s-out/Backend
      # - sed "s|IMAGE_PLACEHOLDER|${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/$FRONTEND_REPO:$IMAGE_TAG|g" $K8S_MANIFEST_DIR/Frontend/deployment.yaml > k8s-out/Frontend/deployment.yaml
      # - cp $K8S_MANIFEST_DIR/Frontend/service.yaml k8s-out/Frontend/service.yaml

      # - sed "s|IMAGE_PLACEHOLDER|${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/$BACKEND_REPO:$IMAGE_TAG|g" $K8S_MANIFEST_DIR/Backend/deployment.yaml > k8s-out/Backend/deployment.yaml
      # - cp $K8S_MANIFEST_DIR/Backend/service.yaml k8s-out/Backend/service.yaml


      # - echo Including database and ingress manifests...
      # - mkdir -p k8s-out/Database
      # - cp $K8S_MANIFEST_DIR/Database/*.yaml k8s-out/Database/
      # - cp $K8S_MANIFEST_DIR/ingress.yaml k8s-out/

      # - echo Aggregating all manifest files into root of k8s-out/ for CodePipeline...
      # - cp k8s-out/Frontend/*.yaml k8s-out/
      # - cp k8s-out/Backend/*.yaml k8s-out/
      # - cp k8s-out/Database/*.yaml k8s-out/

artifacts:
  base-directory: k8s-out
  files:
    - '**/*'

cache:
  paths:
    - 'Application-Code/frontend/node_modules/**/*'
    - 'Application-Code/backend/node_modules/**/*'
